### ISSUE TITLE
Transparency doesn't work with EMI

### ISSUE THREAD

**Issue by JustSimplyKyle** [ruvaldak/AquaHUD#1]
https://github.com/emilyploszaj/emi
idk should this issue to belong to emi or AquaHUD

**Comment by ruvaldak** [comment]
No promises but I'll look into it one day.

**Comment by CodeF53** [comment]
I did some work on my aquahud fork, it looks kinda good, but the nested window style leads to unsightly changes in the translucency.

![image](https://user-images.githubusercontent.com/37855219/184790333-f08c25bb-faed-45f4-8e35-c96fd7079e4f.png)

The dev is planning on moving the text background to a texture so that wont be as bad in the future
![image](https://user-images.githubusercontent.com/37855219/184790575-f59e3a23-798a-4b42-b7e8-b98786748de3.png)

The recipe trees look good with an unmodified version of AquaHud, but I still went and removed the shadows of all of the UI elements they use
![image](https://user-images.githubusercontent.com/37855219/184790794-d61d46eb-b7ca-4ae9-9214-3f93cb80dc9c.png)

@ruvaldak you have permission to use the textures from my commit adding these https://github.com/CodeF53/AquaHUD/commit/09cb2e58b02c212b4225b135046fefba875a539d, you may want to do a few modifications though because my fork is frameless and gridless

**Comment by CodeF53** [comment]
Worth mentioning is that you need to modify create's `gui/jei/widgets.png` to make EMI look half decent for some of its recipes

Without
![image](https://user-images.githubusercontent.com/37855219/184795743-302a58a8-0ad6-452d-97da-f2f755124396.png)
With
![image](https://user-images.githubusercontent.com/37855219/184795768-9c4d92e5-cd18-4c64-9222-495ac659cb68.png)

https://github.com/CodeF53/AquaHUD/commit/95ea2d52b528e12d7721d7f37aa604a6777f1693

**Comment by ruvaldak** [comment]
Make a pull request and I'll look over it. Certainly better than no support at all, I say.

**Comment by ruvaldak** [comment]
This is addressed in [5211d5a](https://github.com/ruvaldak/AquaHUD/commit/5211d5a21cc51c9a512837b94fa87e19ae91e402) - more work will be done on it soon.
